
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://tssavita.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Savita Seetaraman"
title: "{ Savita Seetaraman }"
description: "Blog and website of Savita Seetaraman. Opinions expressed are mine."
# keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "/img/positano.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The past is like a cancelled cheque."
  - text: "Live in the present."

me-img: "/img/savita_new.gif"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
    - image: "/img/timeline/taxyio.png"
      date: "May 2021 - Current"
      description: "Senior DevOps Engineer"
    - image: "/img/timeline/ericsson.png"
      date: "September 2017 - April 2021"
      description: "Open Source Developer"
    - image: "/img/timeline/sap_logo.png"
      date: "June 2016 - April 2017"
      description: "Master thesis student at SAP SE, Walldorf, Germany"
    - image: "/img/timeline/wtm_logo.png"
      date: "July 2016"
      description: "Google Anita Borg Scholar 2016"
    - image: "/img/timeline/sulogo.png"
      date: "December 2015 - February 2016"
      description: "Research Assistant, Saarland University, Germany"
    - image: "/img/timeline/inria_logo.jpg"
      date: "July 2015 - October 2015"
      description: "Student Intern, Madynes, INRIA Nancy, France"
    - image: "/img/timeline/eit_logo.png"
      date: "October 2014 - May 2017"
      description: "Dual Masters in Computer Science & Innovation and Entrepreneurship"
    - image: "/img/timeline/cern_logo.jpg"
      date: "July 2014 - September 2014"
      description: "Computer Security Student Intern, CERN, Switzerland"
    - image: "/img/timeline/gsoc_logo.png"
      date: "May 2014 - August 2014"
      description: "Google Summer of Code 2014 Intern"
    - image: "/img/timeline/erasmus_logo.png"
      date: "September 2013 - June 2014"
      description: "Erasmus Mundus Exchange Student at University of Trento, Italy"
    - image: "img/timeline/amrita_univ_logo.png"
      date: "July 2010 - July 2014"
      description: "Bachelor of Technology in Computer Science and Engineering, Amrita University, India"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "savita.seetaraman5@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Savita Seetaraman - Curious Nerd. Computer science grad. Proud Indian. Open source enthusiast. Music lover. Indian Politics enthusiast. Lover of day trips. Seeker of unexplored landscapes."
author_blurb_image: "/img/savita_new.gif"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/SavitaSeetaraman"
  - title: "twitter"
    url: "https://twitter.com/savitats"
  - title: "github"
    url: "https://github.com/tssavita"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
